/**
 * @fileoverview
 * Provides information about what permissions are required to use specific webhook event.
 *
 * The code in this file is generated with ChatGPT, so it may include some errors.
 *
 * @see https://chat.openai.com/share/34a129f6-f5af-46ff-8cb4-df44ed5a83bb
 */

/**
 * @description
 * Mapping of webhook event ID and required permissions to use it.
 *
 * @see https://developers.cafe24.com/app/front/app/develop/webhook/manage
 */
export const eventScopeTable: Record<number, string[]> = {
  90001: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90002: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90003: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90022: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90023: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90024: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90025: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90026: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90027: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90028: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90029: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90031: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90032: ['mall.read_customer', 'mall.read_personal', 'mall.read_privacy'],
  90033: ['mall.read_community'],
  90034: ['mall.read_community'],
  90035: ['mall.read_community'],
  90036: ['mall.read_community'],
  90037: ['mall.read_community'],
  90038: ['mall.read_community'],
  90039: ['mall.read_community'],
  90041: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90042: ['mall.read_category', 'mall.read_product'],
  90043: ['mall.read_category', 'mall.read_product'],
  90044: ['mall.read_category', 'mall.read_product'],
  90045: ['mall.read_category', 'mall.read_product'],
  90046: ['mall.read_category', 'mall.read_product'],
  90064: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90066: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90068: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90069: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90070: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90071: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90072: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90073: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90074: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90075: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90077: ['mall.read_application'],
  90078: ['mall.read_application'],
  90079: ['mall.read_application'],
  90080: ['mall.read_customer', 'mall.read_personal', 'mall.read_privacy'],
  90084: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_customer',
    'mall.read_order',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90090: ['mall.read_supply'],
  90091: ['mall.read_supply'],
  90092: ['mall.read_supply'],
  90093: ['mall.read_supply'],
  90100: ['mall.read_shipping'],
  90101: ['mall.read_shipping'],
  90102: ['mall.read_shipping'],
  90110: ['mall.read_store', 'mall.read_supply'],
  90111: ['mall.read_store', 'mall.read_supply'],
  90112: ['mall.read_store', 'mall.read_supply'],
  90113: ['mall.read_store', 'mall.read_supply'],
  90114: ['mall.read_store', 'mall.read_supply'],
  90115: ['mall.read_store', 'mall.read_supply'],
  90116: ['mall.read_store', 'mall.read_supply'],
  90117: ['mall.read_store', 'mall.read_supply'],
  90119: ['mall.read_store', 'mall.read_supply'],
  90121: ['mall.read_store', 'mall.read_supply'],
  90142: ['mall.read_store'],
  90143: ['mall.read_customer', 'mall.read_personal', 'mall.read_privacy'],
  90144: ['mall.read_customer', 'mall.read_personal', 'mall.read_privacy'],
  90145: ['mall.read_customer', 'mall.read_personal', 'mall.read_privacy'],
  90146: ['mall.read_customer', 'mall.read_personal', 'mall.read_privacy'],
  90147: ['mall.read_customer', 'mall.read_personal', 'mall.read_privacy'],
  90148: ['mall.read_customer', 'mall.read_personal', 'mall.read_privacy'],
  90150: [
    'mall.read_category',
    'mall.read_collection',
    'mall.read_product',
    'mall.read_promotion',
    'mall.read_supply',
  ],
  90151: ['mall.read_store', 'mall.read_promotion'],
  90152: ['mall.read_store', 'mall.read_promotion'],
  90153: ['mall.read_store', 'mall.read_promotion'],
  90154: ['mall.read_store', 'mall.read_promotion'],
};
